[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn core.wsgi:application --bind 0.0.0.0:%(ENV_PORT)s --workers 1 --access-logfile -
directory=/app/src
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A core worker --loglevel=info --concurrency=1
directory=/app/src
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celerybeat]
command=celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/app/src
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

