# Generated by Django 5.2.15 on 2026-07-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
